### ISSUE TITLE
package restore failure

### ISSUE THREAD

**Issue by ericwscott** [toddams/RazorLight#43]
After upgrading to 1.0.0, I am unable to restore packages.  I get the following error:
```
Version conflict detected for Microsoft.CodeAnalysis.CSharp. 
DemoApp (>= 1.0.0) -> DemoApp.Library (>= 1.0.0) -> RazorLight (>= 1.0.0) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.2) 
DemoApp (>= 1.0.0) -> Microsoft.VisualStudio.Web.CodeGeneration.Design (>= 1.1.0) -> Microsoft.VisualStudio.Web.CodeGeneration.Utils (>= 1.1.0) -> Microsoft.CodeAnalysis.CSharp.Workspaces (>= 1.3.0) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.0).
```
Downgrading to 1.0.0-rc2 resolves the issue.

**Comment by toddams** [comment]
Version conflict messages, usually are just warnings, not errors. Are you sure this is exactly a compilation error?

**Comment by ericwscott** [comment]
It isn't a compilation error.  The nuget package restore fails.

**Comment by KolyaNET** [comment]
I have a similar problem. I returned to version 1.0.0-RC2.

**Comment by toddams** [comment]
Hmm. strange. Investigating...

**Comment by toddams** [comment]
@KolyaNET & @ericwscott 
Can you please share your .csproj file?

**Comment by ericwscott** [comment]
@toddams - I can't share the .csproj file I'm currently using.  I'll see if I can put together a small test that I can share.

**Comment by toddams** [comment]
Any news @ericwscott ?

**Comment by ericwscott** [comment]
I was able to reproduce the problem by creating a new Visual Studio 2017 Asp.Net Core Web Application with Individual Account authentication.  The zipped .csproj file is attached.

The conflict appears to be with:
`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" PrivateAssets="All" />`

[Demo5.zip](https://github.com/toddams/RazorLight/files/910088/Demo5.zip)

**Comment by KolyaNET** [comment]
I use project.json. 
To fix the dependency conflicts, I added the following packages to my project:
```
    "Microsoft.CodeAnalysis.Common": "1.3.2",
    "Microsoft.CodeAnalysis.CSharp": "1.3.2",
    "Microsoft.CodeAnalysis.CSharp.Workspaces": "1.3.2",
    "Microsoft.CodeAnalysis.Workspaces.Common": "1.3.2",
```

**Comment by ericwscott** [comment]
Thanks @KolyaNET.  I added these references to the .csproj file and the package restore is successful.

`<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="1.3.2" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="1.3.2" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="1.3.2" />
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="1.3.2" />`

**Comment by toddams** [comment]
I will add this to FAQ, closing the issue

**Comment by grokky1** [comment]
@KolyaNET I also have this error. Those references include a warning not to include them manually.

Do you believe this is a good long term solution? There might be a better way?

**Comment by KolyaNET** [comment]
@grokky1 No, I do not believe that this is a good solution. But at the moment I do not know another way to solve this problem.

**Comment by grokky1** [comment]
@KolyaNET Yeah me too. I feel this is a workaround, not a solution.

**Comment by toddams** [comment]
I could lower package version to 1.3.0, to avoid the version conflict with asp.net MVC, but who guarantees that one would not use other library/framework that may cause another conflict. This is definitely not a problem of RazorLight, but a nuget that can not deal with using the same package with different versions

**Comment by toddams** [comment]
Ok. Seems like this issue is more annoying that it may appear. Reopening again for further investigation.

**Comment by grokky1** [comment]
@toddams I included the references and forgot about this. But then I saw that those packages have this warning:

> Do not install this package manually, it will be added as a prerequisite by other packages that require it.

So there should be a way for multiple packages to depend on different versions of these dependent packages.

But I'm not sure why it doesn't do that automatically, because in my Visual Studio, under "References", it shows each referenced package, and underneath it which dependent packages it depends on. And there are multiple versions of the same package. So it should be possible.

**Comment by toddams** [comment]
@grokky1 
I uploaded 1.1.0 version. Can you confirm that it resolves the issue?

````install-package Razorlight -version 1.1.0````

**Comment by grokky1** [comment]
@toddams I'm not sure - I'm using "RazorLight.MVC", not "RazorLight". How should I proceed?

**Comment by grokky1** [comment]
@KolyaNET @ericwscott Let us know if new version works for you. @toddams is waiting for confirmation before he also updates the `RazorLight.MVC` package.

**Comment by ericwscott** [comment]
Updated to RazorLight 1.1.0, removed PackageReferences for Microsoft.CodeAnalysis.*.

Package restore completed successfully.  Seems like a good solution to me.

**Comment by KolyaNET** [comment]
@toddams @grokky1 I deleted the packages `Microsoft.CodeAnalysis.*` and updated `RazorLight`. Everything works well. Thank you.

**Comment by grokky1** [comment]
@toddams Looks good... Could we please update `RazorLight.MVC` as well?
